Update tsconfig.json
`forceConsistentCasingInFileLabels` isn't a valid compiler option, as indicated by the following error returned when attempting `pulumi up`:
```
TSError: ⨯ Unable to compile TypeScript:
error TS5023: Unknown compiler option 'forceConsistentCasingInFileLabels'.
```

Replacing this option with `forceConsistentCasingInFileNames` resolves this issue (this option is used in analogous template files for other providers).